# Generated by Django 4.0.6 on 2022-09-13 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.IntegerField()),
                ('account_type', models.CharField(max_length=20)),
                ('account_balance', models.IntegerField()),
                ('account_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=30, null=True)),
                ('symbol', models.CharField(max_length=5, null=True)),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20, null=True)),
                ('email', models.CharField(max_length=15)),
                ('gender', models.CharField(max_length=10)),
                ('age', models.PositiveSmallIntegerField()),
                ('password', models.CharField(max_length=20, null=True)),
                ('id_number', models.IntegerField(null=True)),
                ('nationality', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt', models.CharField(max_length=20)),
                ('date_time', models.DateTimeField()),
                ('bill_number', models.CharField(max_length=20)),
                ('amount', models.IntegerField()),
                ('receipt_file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('customer_id', models.IntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('message', models.CharField(max_length=100)),
                ('date_time', models.DateTimeField()),
                ('points', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('time', models.DateTimeField()),
                ('status', models.CharField(max_length=20, null=True)),
                ('pin', models.IntegerField(null=True)),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallet_currency', to='wallet.currency')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Wallet_customer', to='wallet.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_ref', models.CharField(max_length=20)),
                ('transaction_amount', models.IntegerField()),
                ('transaction_name', models.CharField(max_length=20)),
                ('transaction_type', models.CharField(max_length=20)),
                ('transaction_charge', models.IntegerField()),
                ('receipt', models.CharField(max_length=20)),
                ('destination_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Transaction_destination_account', to='wallet.account')),
                ('original_account', models.ForeignKey(null='true', on_delete=django.db.models.deletion.CASCADE, related_name='Transaction_original_account', to='wallet.account')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Transaction_wallet', to='wallet.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='ThirdParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('amount', models.IntegerField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ThirdParty_account', to='wallet.account')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=20)),
                ('date_time', models.DateTimeField()),
                ('status', models.CharField(max_length=20)),
                ('recipient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Notification_recipient', to='wallet.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_type', models.CharField(max_length=20)),
                ('amount', models.IntegerField()),
                ('interest_rate', models.IntegerField()),
                ('wallet', models.IntegerField()),
                ('loan_balance', models.IntegerField()),
                ('loan_term', models.CharField(max_length=20)),
                ('guarantor', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('payment_due_date', models.IntegerField()),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Loan_transaction', to='wallet.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.IntegerField()),
                ('card_name', models.CharField(max_length=20)),
                ('date_issued', models.DateTimeField()),
                ('card_type', models.CharField(max_length=20)),
                ('expiry_date', models.IntegerField()),
                ('security_code', models.IntegerField()),
                ('issuer', models.CharField(max_length=20)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Card_account', to='wallet.account')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Card_wallet', to='wallet.wallet')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Account_wallet', to='wallet.wallet'),
        ),
    ]
