# Generated by Django 4.0.6 on 2022-08-25 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_account_recipient_reward_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='original_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Transaction_original_account', to='wallet.account'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reward',
            name='message',
            field=models.CharField(max_length=100),
        ),
    ]
