# Generated by Django 4.0.6 on 2022-08-30 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_transaction_original_account_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='date_and_time',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='original_account',
            field=models.ForeignKey(null='true', on_delete=django.db.models.deletion.CASCADE, related_name='Transaction_original_account', to='wallet.account'),
        ),
    ]
